### ISSUE TITLE
Add SVG icons for flags and bombs

### ISSUE THREAD

**Issue by BenMcH** [BenMcH/minesweeper#1]
Instead of the flag and bomb text, I would like these to be SVG icons so that this is easily played on mobile. 

Please share the source of your SVG so that credit can be given if the license requires it.

**Comment by LeonardoBonetti** [comment]
Hello, I would like to solve this Issue, can you assign to me?

**Comment by DeltaHarbinger** [comment]
Hello, I would like to be added to this issue. can I be assigned?

**Comment by BenMcH** [comment]
@DeltaHarbinger I'll assign you if I don't get anything from Leonardo in a few days.

**Comment by LeonardoBonetti** [comment]
I'm just looking for minesweeper free bomb logos, the flag is 100% ready, I will make the PR today

**Comment by DeltaHarbinger** [comment]
Nice job Leonardo. Great use of #hacktober

**Comment by LeonardoBonetti** [comment]
> Nice job Leonardo. Great use of #hacktober

Thank you. for you too

**Comment by DeltaHarbinger** [comment]
If you are still looking for a mine logo, here's one that I found. They even tell you how to credit the author:
https://www.flaticon.com/free-icon/mine_486846?term=mine&page=3&position=1

**Comment by LeonardoBonetti** [comment]
Thank you @DeltaHarbinger

**Comment by LeonardoBonetti** [comment]
@BenMcH  i need to asign pull request to this issue? I never solved a Issue before (PR https://github.com/BenMcH/minesweeper/pull/3)

**Comment by BenMcH** [comment]
I can hook it up for you 😄 you just have to add "closes #issuenumber" in the pr body

**Comment by BenMcH** [comment]
Thank you Leonardo! Your changes are live at https://minesweeper.mchone.dev
