### ISSUE TITLE
Add animations to the clearing of cells via framer motion

### ISSUE THREAD

**Issue by BenMcH** [BenMcH/minesweeper#2]
I believe that it would be neat to have this game animate with framer motion. Go nuts!

**Comment by Balaguru4580** [comment]
Sounds fun! Mind if I take a look at it?

**Comment by BenMcH** [comment]
@Balaguru4580 go for it! I don't have any preference between animation styles, so have fun with it.

**Comment by Balaguru4580** [comment]
Hey, just a small issue. I'm not able to compile the app because of the `Parameter 'cell' implicitly has an 'any' type` errors. I was able to use `@ts-ignore` for the import errors, but this one still confuses me. 

Any help would be appreciated.

**Comment by BenMcH** [comment]
Feel free to use @ts-ignore and I'll take a look in PR 👍

**Comment by Balaguru4580** [comment]
I've made a new pull request. Thanks for helping me out!
